#dictionaries inside a list
#got this data from https://opentdb.com/api_config.php
question_data = [{"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "&quot;Windows NT&quot; is a monolithic kernel.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
